const User = require('../models/userModel')
const jwt = require('jsonwebtoken')
require('dotenv').config()

const createToken = (_id) => {
    return jwt.sign({_id}, process.env.SECRET, {expiresIn: '3d'})    // payload object, secret, options object // header is generated by jwt by default
}
// login and singup both are of post type as they have body (data) to be processed.
// login user
const loginUser = async (req, res) => {
    const {email, password} = req.body
    try {
        const user = await User.login({email, password})

        // after retrieving the user, create token
        const token = createToken(user._id)
        res.status(200).json({email, token})
    } catch (error) {
        res.status(400).json({error: error.message})
    }
}

// signup user
const signupUser = async (req, res) => {
    const {email, password} = req.body
    try {
        const user = await User.signup({email, password})

        // after creating the user, create token
        const token = createToken(user._id)

        res.status(200).json({email, token})
    } catch (error) {
        console.log(error.message)
        res.status(400).json({error: error.message})
    }

}

module.exports = {loginUser, signupUser}